### ISSUE TITLE
Name-based discrimination of inputs to streams: observable or container

### ISSUE THREAD

**Issue by ivan-kleshnin** [staltz/cycle#102]
I wonder why this works:
```javascript
let Model = function () {
  let min$ = Stream(PropsMin$ => PropsMin$);
  let max$ = Stream(PropsMax$ => PropsMax$);
  return {
    min$, max$,
    inject(Props) {
      min$.inject(Props.get('min$'));
      max$.inject(Props.get('max$'));
  }};
}();
```

And this:
```javascript
let Model = function () {
  let min$ = Stream(Props => Props.get('min$'));
  let max$ = Stream(Props => Props.get('max$'));
  return {
    min$, max$,
    inject(Props) {
      min$.inject(Props);
      max$.inject(Props);
  }};
}();
```
yields **Props.get is not a function**.

Is the `Stream` input implicitly expected to be an Observable only? 

I believe second variant is better because it opens possibility to abstract injection stuff under some `Streams` shortcut. Not saying it also frees your from creating new variable names which is boresome and looks cleaner.

It could be like this:

```javascript
let Model = function () {
  let min$ = Stream(Props => Props.get('min$'));
  let max$ = Stream(Props => Props.get('max$'));
  return Streams({min$, max$}, ["Props"]);
}();
```

**Comment by staltz** [comment]
This is unfortunately not possible to fix unless we: (1) go back to the pre-stream-branch API, (2) use ES6 Proxies. Because:

> Is the Stream input implicitly expected to be an Observable only?

Yes. This assumption is what allows us to get rid of all the getters that were previously needed. The way Cycle.createStream(definitionFn) works is by creating a proxy Observable for each of the input parameters given to the definitionFn, based only on definitionFn.length.

**Comment by ivan-kleshnin** [comment]
Can't we decide by parameter name? JS has access to that meta information and if `$` is required as observable mark that shouldn't be a problem. So if param ends with `$` it's an observable. 
If not – it's a collection of observables.

**Comment by staltz** [comment]
> Can't we decide by parameter name? JS provides access to that meta information

How?

**Comment by ivan-kleshnin** [comment]
There seems a lot of a ways, but all of them are based on `func.toString` syntax parsing:
http://stackoverflow.com/questions/914968/inspect-the-names-values-of-arguments-in-the-definition-execution-of-a-javascrip

**Comment by danyx23** [comment]
Hm, that does sound a bit like magic - and not having magic is just what I like about cycle. OTOH it may be nice for future convenience layers if there were a way to pack several streams together.

**Comment by ivan-kleshnin** [comment]
```javascript
function annotate(func) {
  var funStr = func.toString();
  return funStr.slice(funStr.indexOf('(')+1, funStr.indexOf(')')).match(/([^\s,]+)/g);
}

console.log(annotate(() => true));
console.log(annotate((x) => true));
console.log(annotate((x, x$) => true));

console.log(annotate(function () { return true; }));
console.log(annotate(function (x) { return true; }));
console.log(annotate(function (x, x$) { return true; }));

null
[ 'x' ]
[ 'x', 'x$' ]
```

**Comment by ivan-kleshnin** [comment]
1) Angular uses this as far as I know
2) This may be removed with Proxies 
3) Current situation requires too much boilerplate code as your BMI example perfectly demonstrates. 
Too much noise. Something need to be improved here.

**Comment by danyx23** [comment]
I agree that the amount of boilerplate is too high ATM.

Could Prop be an observable stream of an object that contains the prop key value pairs? As in 

```
registerCustomElement("slider", (rootElement$, props$) => {
```

**Comment by ivan-kleshnin** [comment]
I don't know why we have `Props.get` syntax. Because of possible dashes in `data-xxx` attrs? No, that may be solved with `[]` access. @staltz please explain.

**Comment by ivan-kleshnin** [comment]
Remarshalling of every `Prop` key into `Model` just to set `startWith` is extremely annoying.
This will kill anyone on production. React syntax of `{...props}` is a dream.

**Comment by staltz** [comment]
First of all: thanks a lot @ivan-kleshnin for this type of sparring and suggestions for the API. I really appreciate someone challenging me while being honest with what sucks.

I was hoping that the "How?" question for meta information on a function would not have been "fn.toString()", maybe there would have been another way. But once in a while I'm reminded that JS still sucks. Proxy will make it suck less, but we need to live without it for now.

I'm probably 80% convinced by now that we should use fn.toString() to reduce boilerplate. Cycle's framework codebase got much smaller with this Streams refactor, and app boilerplate has increased I would say at a perceived rate of 110% (even though other local use cases boilerplate has been reduced by perceived 60%). So we should probably do something against boilerplate. I think we can do this: "So if param ends with $ it's an observable. If not – it's a collection of observables." However, a collection of observables means just an object with a getter function.

> I don't know why we have Props.get syntax. Because of possible dashes in data-xxx attrs? No, that may be solved with [] access. @staltz please explain.

The getter is really needed. The custom element `definitionFn(rootElem$, props)` is called when the custom element is first rendered in the virtual DOM. The custom element might have been created with, e.g., `h('my-slider', {min: 0, max: 100})`, but subsequent uses of it might look like `h('my-slider', {min: 0, max: 100, value: 37})`. But definitionFn needs to handle all possible properties when it is called, to set all the wiring for the future.

The only way I see to get rid of the getter is to use a Proxy. This also counts for those "collection of observables" mentioned above.

**Comment by ivan-kleshnin** [comment]
Thanks @staltz, your explanation why `Props.get` is currently required is clear.
I also believe there should be some way to generalize `InputProxy` and `PropertiesProxy` to allow `inject(Props)` syntax without `$` checking.

**Comment by staltz** [comment]
> I still believe there should be some way to generalize InputProxy and PropertiesProxy to allow inject(Props) syntax without $ checking.

If you find that, I would be happy.

**Comment by staltz** [comment]
Not relevant anymore after v0.20
