### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by kenaiX** [staltz/cycle#105]
very very thanks for your article https://gist.github.com/staltz/868e7e9bc2a7b8c1f754

but i meet some trouble

how rxjava work in touch event ?

this is my code :

```
public class RxJavaActivity extends Activity{

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        Observable.just(event)
                .buffer(2)
                .map(List::size)
                .subscribe(integer -> Log.e("test", "" + integer));
        return true;
    }
}
```

it not work ...
every time it return "1"

**Comment by staltz** [comment]
Sorry, this is a RxJava question. Do it in StackOverflow please
