### ISSUE TITLE
Use event.detail property for carrying custom event data

### ISSUE THREAD

**Issue by pH200** [staltz/cycle#124]
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/initCustomEvent

http://www.w3.org/TR/dom/#interface-customevent

We should use `detail` for custom event's data since it's more standard and prevents modifying event object after it's created.

**Comment by staltz** [comment]
Yes, agreed.
Reminder to self: https://github.com/staltz/cycle/blob/896ce02b67d15b7e5297d81e99dd204fd774001d/src/custom-element-widget.js#L15

**Comment by staltz** [comment]
Done in v0.22
