### ISSUE TITLE
Writing the name of the streams three times each is too much boilerplate

### ISSUE THREAD

**Issue by fiatjaf** [staltz/cycle#40]
For instance, the example at [README.md](https://github.com/staltz/cycle/blob/7a8953719ca2b881d37f0b100e4c8596bdd42f4d/README.md) has `'inputText$'` written three times.

If you have a lot of events happening, you not only have to give unique names to them, you also need to write these names on a lot of disconnected places. It is not optimal and refactoring is too difficult.

I've been thinking about it, but I don't have a solution, so I'll just leave this issue here.

**Comment by staltz** [comment]
@fiatjaf this is fixed in (upcoming) v0.8.0
