### ISSUE TITLE
How does this work in a larger app?

### ISSUE THREAD

**Issue by gaearon** [staltz/cycle#45]
I have basic knowledge of Rx and some experience with Flux. Though I don't quite enjoy the tone of your presentation, I find the way you compose things in Cycle very interesting and would like to learn more.

My question is how a larger application would be structured. (I guess, a port of FB Flux chat example to Cycle would be *very* helpful.)

For example, if there are ten components that want to "follow user", is it correct that I would:

* Inject them all into `FollowUserIntent`
* Have them all export `followUserClick$` with the same name so same intent works for them?

Or would I rather have different intents, each for a specific component, but have `FollowUserIntent` subscribe to these intents?

**Comment by neverfox** [comment]
What happened to the FAQ that was linked to above?

**Comment by staltz** [comment]
Most questions and answers in the FAQ got deprecated as the framework evolved, and the useful Q&As got incorporated into the docs site as gray boxes placed in the middle of text, in proper context. @neverfox
