### ISSUE TITLE
Wisp with browserify (and wispify or similar) for browser bundles

### ISSUE THREAD

**Issue by mariusk** [staltz/cycle#50]
I'm trying to get a build pipeline going using wisp and browserify, and it seems browserify is unable to pick up and auto-include the required dependencies. Has anybody succeeded in building browser bundles with the resulting javascript code (after running through wisp)?

**Comment by staltz** [comment]
Browserify is now at version 8.0.2 in Cycle.

**Comment by egasimus** [comment]
@mariusk I'm not using Cycle (although after reading the proposition in the README I am seriously considering it). However I'm seeing the same problem when trying to import Wisp modules from other Wisp modules using wispify so you might want to raise the issue [there](https://github.com/conradz/wispify/issues) :)

**Comment by egasimus** [comment]
@mariusk: Actually, after some more Googling, I found [this Stackoverflow question](http://stackoverflow.com/questions/16110750/how-to-perform-a-transform-on-npm-module-using-browserify); which made me realize that I needed to set `{ global: true }` in the options to `browserify.transform`, as briefly mentioned [here](https://github.com/substack/node-browserify#btransformtr-opts). Sure enough, having done that, my cross-module Wisp imports have started working.
