### ISSUE TITLE
Any estimate for when cycle reaches 1.0?

### ISSUE THREAD

**Issue by qur2** [staltz/cycle#59]
Everything is in the title. At the moment, how stable/mature is the project?

I read the seminal blog post that led to the creation of the framework and I'm highly interested.

Thank you and happy new year.

**Comment by staltz** [comment]
Time estimate? None
Feature estimate? Roughly the following:

- [ ] Reduced boilerplate #56 
- [ ] Server-side rendering (HTMLRenderer)
- [ ] Memory optimizations
- [ ] (Cycle used in production in a couple of real apps, to find and fix bugs and performance issues)

So at the moment it is unstable, specially regarding the API and performance.

**Comment by qur2** [comment]
Great, thanks. I leave the closing of the ticket up to you, just in case you wanna keep it open for updates.
