### ISSUE TITLE
replicate VS publish/connect

### ISSUE THREAD

**Issue by qur2** [staltz/cycle#60]
I'm new to RxJS, so please be forgiving.
I'm implementing a small app modelled after the futurice blog post. I understand why the replicate function is used (to avoid circular dependency and be able to plug the components when the app is initialized, right?) and I'm wondering why not using the publish/connect from "hot" observable?

I checked in cycle and the replicate function is there as well. I know this function provides a solution that works fine, I'm trying to get my hands dirty in order to really understand what's going on.

Thank you.

**Comment by staltz** [comment]
The reason why replicate() exists is that we need a proxy for the input to a DataFlowNode. Once the real input is injected into the DataFlowNode, we need to "copy and paste" all events from the real input to the proxy input. replicate() is the "copy and paste".

**Comment by qur2** [comment]
Thanks for the explanation. I think I was also confused about what a subject is to an observable, but that's more a RxJS understanding issue.
