### ISSUE TITLE
replaceCustomElements fails with a VirtualText node

### ISSUE THREAD

**Issue by dobrite** [staltz/cycle#62]
`vtree.tagName` is undefined so calling `toUpperCase()` fails with:

> Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

So check for existence prior to use.

introduced in commit: 6c801af9c880be4744c8d48a1a1b5fe80b3df13d

:beers:

**Comment by staltz** [comment]
@dobrite v0.8.1 released to fix this.
