### ISSUE TITLE
Why use RXJS over JS-CSP?

### ISSUE THREAD

**Issue by zoomclub** [staltz/cycle#74]
I've been learning about JS-CSP and in the process trying to discover how to use my document data in Firebase as a source for streams. The discovery process has lead me to something called RXJS, which seems similar to JS-CSP in many ways. Except JS-CSP has channels and is suitable for working with concurrent processes.

http://jlongster.com/Taming-the-Asynchronous-Beast-with-CSP-in-JavaScript

It is most interesting to see your use of RXJS in Cycle, as well I found the following link where RXJS is used to actually turn Firebase data into streams: http://blog.cryptoguru.com/2014/11/frp-using-rxjs-and-firebase.html

My open issue on the JS-CSP site is here: https://github.com/ubolonton/js-csp/issues/30

It looks like the heart of the issue is concerned with how to turn Firebase data into streams. Then the next question I have is why use RXJS instead of JS-CSP?

**Comment by joelhooks** [comment]
He says in [the article](http://futurice.com/blog/reactive-mvc-and-the-virtual-dom):

> I prefer RxJS for its language ubiquity, but your mileage may vary.

Reactive Extensions is interesting because its API carries across many platforms, so you can "learn once" and apply it in many contexts.

Not to speak for @staltz, but that is my guess :smile:

**Comment by staltz** [comment]
Yeah it's a matter of taste.

I wrote [here](https://github.com/arqex/curxor/issues/1#issuecomment-72642125):
> Reactive programming is simply about decoupling data production from data consumption, so a module (or some "part" of your app) can choose what data is it interested in consuming whenever that data changes. With typical imperative programming, when data is produced, the producer has to explicitly know its consumers and explicitly ask them to update.

>Hence you can use simple event emitters with listeners to implement reactive programming. But as I said in the article, Event emitters as slingshots, while event streams with operators (Rx, Bacon, Kefir, Highland) are semi-automatic sub-machine guns.

>CSP channels go beyond and decouple 3 things: data production, data medium, data consumption. It has its benefits, but you can also choose to decouple the data medium with Rx et al, so then CSP versus event stream processing becomes just a matter of taste.

**Comment by zoomclub** [comment]
Great! I'm glad to know that we have these reactive APIs available now, they are absolutely required for modern apps. Prior to this the best was just trying to fit a circle in a square, it is difficult when there is a required vision for a product but poor means to achieve it. Glad those times are fading and the future will be entirely reactive :)

**Comment by nmn** [comment]
There are some differences and many similarities between js-csp and RxJS. They are both stream interfaces that can be treated as any other set of data, and so you can use common methods like map and filter. (also throttle and debounce)

The main differences are:
- js-csp is dependent on generator functions, RxJS is not.
- js-csp creates pipes from single senders to single receivers by default. RxJS streams can be used many times and are by default one to many streams.
- js-csp is a small concept that is then built on by many helper functions. (these helper functions can come in various forms, transducers being just one) RxJS, basically needs to be used as a whole large library.

I've written more about how, channels can be used more like RxJS streams in this issue:
https://github.com/ubolonton/js-csp/issues/40

**Comment by staltz** [comment]
Thanks @nmn for the summary on the differences. Highlighted some stuff I didn't know about :)
