### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by ivan-kleshnin** [staltz/cycle#80]
I have one-file **`app.js`** where I do `require('cyclejs')`. As code is in ES6 it doesn't work in browser.
`$ browserify app.js -t babelify --outfile bundle.js` ignores everything in **`node_modules`** and doesn't convert **cyclejs** code without adding to **`node_modules/cyclejs/package.json`**:

```javascript
"browserify": {
  "transform": [["babelify", {"experimental": true, "sourceMapRelative": "."}]]
}
```

So how it's supposed to be used in CommonJS style apps?

**Comment by staltz** [comment]
This is a bug and our mistake. Will try to get this fixed ASAP.

**Comment by staltz** [comment]
@ivan-kleshnin try [v0.15.3](https://github.com/staltz/cycle/releases/tag/v0.15.3) which should fix this.

**Comment by ivan-kleshnin** [comment]
Confirmed
