### ISSUE TITLE
Strange event bug

### ISSUE THREAD

**Issue by ivan-kleshnin** [staltz/cycle#87]
I discovered strange bug which may be either related CycleJS or some tricky case in my own code. 
Or even be a bug in virtual DOM. I don't know yet.

In example with multiple sliders (e.g. this https://github.com/ivan-kleshnin/cyclejs-examples/tree/master/src/3.4-slider-colors) sliders not always react on deletion.
`Slider` sends `remove` event but global `Intent` does not get it.

Video proof: https://docs.google.com/file/d/0B9bW0B92XgnASmNTbzZWM216cWM/edit

The strangest thing about it is that this behavior looks undeterministic. That's why I say there is a chance about some desync between virtual DOM nodes. Sometimes it works and sometimes not. The only fact I found by trial is that first render works ok. Removals before first addition worked in 100% cases.

**Comment by staltz** [comment]
At first thought I was about to suggest you need to add the `key` to every Slider, but you are already doing that. I need to debug this. I think I have time today to take a look.

**Comment by staltz** [comment]
I can reproduce the bug and I can confirm it's a real bug in Cycle. I'm working on it.

**Comment by staltz** [comment]
Good news: I found a proper fix for the bug.
Not so good news: I'm going to take more time to make proper automated tests for these stuff, and won't release the bug fix before I have these tests, so you will have to wait a bit until the tests + bug fixes are ready.

**Comment by staltz** [comment]
If you're curious, this is the fix: https://github.com/staltz/cycle/commit/b2d1b704df383f36c4a9c3d5043913a8bcb04555

**Comment by ivan-kleshnin** [comment]
> so you will have to wait a bit until the tests + bug fixes are ready

That's ok. I'm happy I've not tried to debug this: very involved stuff :smile:

**Comment by ivan-kleshnin** [comment]
Sadly, this fix branch does not include no `/lib` nor `/src` so this is again incompatible with browserify.

**Comment by staltz** [comment]
@ivan-kleshnin can you test with [v0.16.3](https://github.com/staltz/cycle/releases/tag/v0.16.3) ?

**Comment by ivan-kleshnin** [comment]
@staltz, sure

**Comment by ivan-kleshnin** [comment]
@staltz I checked 0.17.0 against my examples. 
Everything looks fine, #87 and #89 are gone :thumbsup:

**Comment by staltz** [comment]
Good :)
