### ISSUE TITLE
Recommendations about implicit state

### ISSUE THREAD

**Issue by ivan-kleshnin** [staltz/cycle#93]
Working with Cycle I often find myself in situation where some issue can be solved with either implicit or explicit state. For example, we have a toggler. Toggler has 2 states: favorite and non-favorite. 

#### Implicit state
Intent relies on HTML class to produce both `favup$` and `unfav$` observables.
So some state is implicitly encapsulated in DOM. This reminds our old days with jQuery where ALL state was in DOM so DOM served as XML database. It was imperfect, though worked to some degree.
Short: fat Intent, skinny Model.

#### Explicit state
Intent produce just `toggle$` observable. It's a model purpose to decipher it. In many cases will require to have `scan` in Model, because `scan` is one of the few stateful methods.
Short: skinny Intent, fat Model.

Second option is probably both more complex and more "idealistic". On the other hand, Intent barely deserves it's name when it's completely pure and state agnostic...

This question is obviously non-Cycle specific.
But I wonder: are both approaches conventional from the author point of view? 
If implicit state is properly encapsulated, can it still cause some unwanted consequences later? 
Should we avoid implicit DOM state in Cycle whenever possible or not?
Or both are fine and it's a developer task to decide when it's time to switch from Implicit to Explicit?

**Comment by staltz** [comment]
> But I wonder: are both approaches conventional from the author point of view? 

I prefer explicit. Skinny Intent is not a problem. Sometimes it really is skinny (specially on click events), sometimes it's not (when doing voice recognition for instance, you need to run an algorithm. The best place to put it in is Intent).

> If implicit state is properly encapsulated, can it still cause some unwanted consequences later? 

If it causes some unwanted consequences, then it's not properly encapsulated. ;)

> Should we avoid implicit DOM state in Cycle whenever possible or not?

Yes we should avoid.

> Or both are fine and it's a developer task to decide when it's time to switch from Implicit to Explicit?

I recommend explicit, and to clarify some potential fears: Cycle is not optimized for minimal boilerplate nor productivity. It's optimized for separation of concerns. If a developer wants to speed up his development processes, he will often find himself mixing concerns, taking shortcuts. Cycle is not a framework for those types of shortcuts, unfortunately (or fortunately). I'm not saying they are a bad thing, I'm just saying Cycle is not the right tool for that if maximum productivity is a requirement.

**Comment by ivan-kleshnin** [comment]
Thanks! There is often a blurry difference between two but it's valuable to keep some "best practices" in mind.

**Comment by cgeorg** [comment]
"Maximum productivity" as defined by maximum code output today, or maximum system functioning over time?  They are rarely the same.

**Comment by ivan-kleshnin** [comment]
What about stateful components? Every time I created additional state loops like this:
```
[Click] <- Component State <- App State <- Component State
```
I got very fragile and buggy behavior. So my experience leads to conclusion to avoid stateful components at all costs. But what about WebComponens, aren't they meant to have state? And this state should be somehow incorporated into app state...

**Comment by staltz** [comment]
> I got very fragile and buggy behavior. So my experience leads to conclusion to avoid stateful components at all costs.

Whenever you don't need state in components, don't put state in components. Otherwise that would be accidental complexity. But if you are dealing with essential complexity, than you can't sensibly avoid stateful components, so you should do it in the right and cleanest possible way. Most of the times it's best solved by deciding what is the best place to put state.

I recommend checking how I solved this in RxMarbles: https://github.com/staltz/rxmarbles/tree/master/src/components specially the interplay between Diagram component (its intent and model) and the Marble component.

**Comment by ivan-kleshnin** [comment]
@staltz there are also cases when complexity is faked for learning purposes u know.
I have [this toggle sandbox](https://github.com/ivan-kleshnin/cyclejs-examples/tree/master/examples/6.2-favs-list), where state is duplicated in component and app.
Of course this complexity is accidental but as an emulation for real-world cases. 

And I can't figure out whether [this problems](https://drive.google.com/file/d/0B9bW0B92XgnAM0lCOXZUUXA4Mnc/view) are app problems or something connected with VDOM. 
It would be great if you took a look.

**Comment by staltz** [comment]
Quick check: have you forgot to use `key` for custom elements?

**Comment by ivan-kleshnin** [comment]
Yes, good catch. This time I forgot it and that was a reason. 
Can we made React-like warning about missing ref? It would help a lot.

**Comment by staltz** [comment]
> Can we made React-like warning about missing key? It would help a lot.

Good idea, I'll make an issue for that.

(do you mind if I close this issue? We can reopen if needed)
