### ISSUE TITLE
Sources are excluded from NPM

### ISSUE THREAD

**Issue by ivan-kleshnin** [staltz/cycle#94]
Why? I'd like to have ES6 version of CycleJS sources near at hand.
Especially considering current GitHub accessibility issues ;)

**Comment by staltz** [comment]
Hmm, good point. I guess src is unnecessary for npm (I think I was trying to avoid unnecessary kilobytes to download when `npm install cyclejs`). But if you consider it important, fine. I wonder if someone else will find it annoying/confusing to have both lib and src.

**Comment by staltz** [comment]
Should be fixed now in v0.18.1
