### ISSUE TITLE
Raise warning whenever a custom element is used without a key

### ISSUE THREAD

**Issue by staltz** [staltz/cycle#96]
See https://github.com/staltz/cycle/issues/93#issuecomment-87469293

**Comment by ivan-kleshnin** [comment]
Btw it's seems strange to me that every custom element should be used only with a key.
React requires keys only when elements (no matter custom or not) are created in a loop e.g. `map`.
In other cases I experienced no warnings and no problems without keys. Can it be that this key requirement is just a "patch" over more fundamental architectural issue? Can it be reviewed again with the new Cycle architecture?

**Comment by staltz** [comment]
I can review it yes. But keep in mind React always has keys, they are `reactid` attributes on the DOM. virtual-dom and Cycle don't.
