### ISSUE TITLE
Access to children elements from custom element.

### ISSUE THREAD

**Issue by ivan-kleshnin** [staltz/cycle#97]
Exact API is to be decided. Basically, we declare custom element tree like this:

```javascript
<Menu>
  <MenuItem>Home</MenuItem>
  <MenuItem>About us</MenuItem>
  <MenuItem>Contacts</MenuItem>
</Menu>
```

JSX transform converts this to:

```javascript
h('Menu', {}, [
  h("MenuItem", {}, ["Home"]),
  h("MenuItem", {}, ["About Us"]),
  h("MenuItem", {}, ["Contacts"]),
])
```

Now we want to access `MenuItem` elements from inside `registerCustomElement` -> `definitionFn`.
React provides such access through `props.children`, but I would suggest to consider additional argument to `definitionFn` because React-like mix of tag arguments and tag content did receive some valid criticism. 

On the flip side, the type of this argument is hard to decide:
```javascript
registerCustomElement("Menu", function(User, Properties, children$) {
  ??? 
});

registerCustomElement("Menu", function(User, Properties, Children) {
  Children.get("0$") ??? ^_^
  Children.get("1$") ???
  Children.getAll() ???
});

registerCustomElement("Menu", function(User, Properties, Children) {
  Children.get() ???
});

???
```

**Comment by staltz** [comment]
Yes, we should build that, and I think it should be accessible as `Properties.get('children$')`, where `children$` is an Observable of VTrees, so if you provided a sequence of elements, you will get an array of vtrees emitted on children$.

**Comment by staltz** [comment]
Built in [v0.18.2](https://github.com/staltz/cycle/releases/tag/v0.18.2) ping @ivan-kleshnin

**Comment by staltz** [comment]
The implementation was one line of code :)
https://github.com/staltz/cycle/commit/fc9177a7e8fddfcc66749a4d55f07d653bcbd812#diff-315780b833431607fea8e015f6df4350R100

**Comment by ivan-kleshnin** [comment]
Thanks :grinning:
